export const Colors = {
    light: {
        background: "#FFFFFF",
        surface: "#FFFFFF",
        headerBg: "#FFFFFF",
        chipBg: "#F2F2F2",
        chipActiveBg: "#0F0F0F",
        chipText: "#0F0F0F",
        chipActiveText: "#FFFFFF",
        textPrimary: "#0F0F0F",
        textSecondary: "#606060",
        border: "#E5E5E5",
        skeleton: "#E5E5E5",
        skeletonHighlight: "#F5F5F5",
        iconColor: "#030303",
        statusBar: "dark-content",
    },
    dark: {
        background: "#0F0F0F",
        surface: "#0F0F0F",
        headerBg: "#0F0F0F",
        chipBg: "#373737",
        chipActiveBg: "#F1F1F1",
        chipText: "#F1F1F1",
        chipActiveText: "#0F0F0F",
        textPrimary: "#F1F1F1",
        textSecondary: "#AAAAAA",
        border: "#373737",
        skeleton: "#373737",
        skeletonHighlight: "#444444",
        iconColor: "#030303",
        statusBar: "light-content",
    },
} as const;